In [2]:
import numpy as np
import pandas as pd

# priv=40, k=100

In [6]:
sample_size_vec = [10000, 20000, 30000, 40000, 50000]
power_array_priv_40_k_100 = np.zeros([5,8])
for i, sample_size in enumerate(sample_size_vec):    
    filename = 'C:/Users/Jongmin/Documents/GitHub/LDPUts/simul/power/gaboardi/k_100/priv_40/p_value_array_priv_40_k_100_n_' + str(sample_size) + '.npy'
    p_value_vec = np.load(filename)
    power_array_priv_40_k_100[i,np.arange(1,7+1)] = (p_value_vec<0.05).mean(axis = 0)
power_array_priv_40_k_100[:,0 ] = 10000*np.arange(1,5+1)
power_array_priv_40_k_100 = pd.DataFrame(power_array_priv_40_k_100)
power_array_priv_40_k_100.columns = ["sample_size", "LapU", "discLapU",  "genRR_perm", "genRR", "bitflip_perm", "bitflip",  "truncNorm"]
power_array_priv_40_k_100.to_csv("C:/Users/Jongmin/Documents/GitHub/LDPUts/simul/power/gaboardi/k_100/priv_40/power_array_priv_40_k_100.csv", index = False)

# k= 100, priv= 0.5

In [8]:
sample_size_vec = [10000, 20000, 30000, 40000, 50000]
power_array = np.zeros([5,8])
for i, sample_size in enumerate(sample_size_vec):    
    filename = 'C:/Users/Jongmin/Documents/GitHub/LDPUts/simul/power/gaboardi/k_100/priv_05/p_value_array_priv_05_k_100_n_' + str(sample_size) + '.npy'
    p_value_vec = np.load(filename)
    power_array[i,np.arange(1,7+1)] = (p_value_vec<0.05).mean(axis = 0)
power_array[:,0 ] = 10000*np.arange(1,5+1)
power_array = pd.DataFrame(power_array)
power_array.columns = ["sample_size", "LapU", "discLapU",  "genRR_perm", "genRR", "bitflip_perm", "bitflip",  "truncNorm"]
power_array.to_csv("C:/Users/Jongmin/Documents/GitHub/LDPUts/simul/power/gaboardi/k_100/priv_05/power_array_priv_05_k_100.csv", index = False)

# k = 40, priv = 1.0

In [12]:
sample_size_vec = [20000, 40000]
power_array = np.zeros([2,8])
for i, sample_size in enumerate(sample_size_vec):    
    filename = 'C:/Users/Jongmin/Documents/GitHub/LDPUts/simul/power/gaboardi/k_40/priv_10/p_value_array_priv_10_k_40_n_' + str(sample_size) + '.npy'
    p_value_vec = np.load(filename)
    power_array[i,np.arange(1,7+1)] = (p_value_vec<0.05).mean(axis = 0)
power_array[:,0 ] = [20000, 40000]
power_array = pd.DataFrame(power_array)
power_array.columns = ["sample_size", "LapU", "discLapU",  "genRR_perm", "genRR", "bitflip_perm", "bitflip",  "truncNorm"]
power_array.to_csv("C:/Users/Jongmin/Documents/GitHub/LDPUts/simul/power/gaboardi/k_40/priv_10/p_value_array_priv_10_k_40.csv", index = False)

# k = 2000, priv = 2.0

In [19]:
power_array_lapu_ell2 = np.load("C:/Users/Jongmin/Documents/GitHub/LDPUts/simul/power/gaboardi/k_2000/p_value_array_priv_lapu_ell2_priv_20_k_2000_n_200000high_sig.npy")
power_array_bitflip_ell2 = np.load("C:/Users/Jongmin/Documents/GitHub/LDPUts/simul/power/gaboardi/k_2000/p_value_array_priv_bitflip_ell2_priv_20_k_2000_n_200000high_sig.npy")
power_array_bitflip_chi = np.load("C:/Users/Jongmin/Documents/GitHub/LDPUts/simul/power/gaboardi/k_2000/p_value_array_priv_bitflip_priv_20_k_2000_n_200000_high_sig.npy")


(power_array_lapu_ell2<0.05).mean(axis = 0)


array([0.16666667])

In [17]:
(power_array_bitflip_ell2<0.05).mean(axis = 0)


array([0.52])

In [18]:
(power_array_bitflip_chi<0.05).mean(axis = 0)

array([0.69333333])