In [1]:
import sys
sys.path.insert(0, '/mnt/nas/users/mjm/LDPUts')

from discretizer import discretizer
from client import client
import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
import matplotlib.pyplot as plt
from server import server_ell2, server_multinomial_genrr, server_multinomial_bitflip
from data_generator import data_generator
from discretizer import discretizer
import time
import numpy as np
from scipy.stats import chi2
from utils import chi_sq_dist

In [2]:

n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 50000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_40_k_100_n_50000 = np.zeros([n_test, 7])

privacy_level = 4.0

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_40_k_100_n_50000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_40_k_100_n_50000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_40_k_100_n_50000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_40_k_100_n_50000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_40_k_100_n_50000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_40_k_100_n_50000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_40_k_100_n_50000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_40_k_100_n_50000)


tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

# n=40000, privacy level = 4

In [3]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 40000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_40_k_100_n_40000 = np.zeros([n_test, 7])

privacy_level = 4.0

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_40_k_100_n_40000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_40_k_100_n_40000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_40_k_100_n_40000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_40_k_100_n_40000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_40_k_100_n_40000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_40_k_100_n_40000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_40_k_100_n_40000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_40_k_100_n_40000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

In [4]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 30000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_40_k_100_n_30000 = np.zeros([n_test, 7])

privacy_level = 4.0

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_40_k_100_n_30000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_40_k_100_n_30000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_40_k_100_n_30000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_40_k_100_n_30000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_40_k_100_n_30000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_40_k_100_n_30000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_40_k_100_n_30000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_40_k_100_n_30000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

In [5]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 20000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_40_k_100_n_20000 = np.zeros([n_test, 7])

privacy_level = 4.0

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_40_k_100_n_20000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_40_k_100_n_20000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_40_k_100_n_20000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_40_k_100_n_20000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_40_k_100_n_20000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_40_k_100_n_20000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_40_k_100_n_20000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_40_k_100_n_20000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

In [6]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 10000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_40_k_100_n_10000 = np.zeros([n_test, 7])

privacy_level = 4.0

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_40_k_100_n_10000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_40_k_100_n_10000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_40_k_100_n_10000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_40_k_100_n_10000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_40_k_100_n_10000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_40_k_100_n_10000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_40_k_100_n_10000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_40_k_100_n_10000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

In [7]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 50000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_20_k_100_n_50000 = np.zeros([n_test, 7])

privacy_level = 2.0

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_20_k_100_n_50000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_20_k_100_n_50000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_20_k_100_n_50000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_20_k_100_n_50000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_20_k_100_n_50000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_20_k_100_n_50000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_20_k_100_n_50000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_20_k_100_n_50000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

In [8]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 40000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_20_k_100_n_40000 = np.zeros([n_test, 7])

privacy_level = 2.0

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_20_k_100_n_40000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_20_k_100_n_40000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_20_k_100_n_40000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_20_k_100_n_40000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_20_k_100_n_40000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_20_k_100_n_40000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_20_k_100_n_40000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_20_k_100_n_40000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

In [9]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 30000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_20_k_100_n_30000 = np.zeros([n_test, 7])

privacy_level = 2.0

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_20_k_100_n_30000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_20_k_100_n_30000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_20_k_100_n_30000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_20_k_100_n_30000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_20_k_100_n_30000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_20_k_100_n_30000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_20_k_100_n_30000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_20_k_100_n_30000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

In [10]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 20000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_20_k_100_n_20000 = np.zeros([n_test, 7])

privacy_level = 2.0

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_20_k_100_n_20000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_20_k_100_n_20000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_20_k_100_n_20000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_20_k_100_n_20000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_20_k_100_n_20000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_20_k_100_n_20000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_20_k_100_n_20000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_20_k_100_n_20000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

In [11]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 10000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_20_k_100_n_10000 = np.zeros([n_test, 7])

privacy_level = 2.0

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_20_k_100_n_10000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_20_k_100_n_10000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_20_k_100_n_10000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_20_k_100_n_10000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_20_k_100_n_10000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_20_k_100_n_10000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_20_k_100_n_10000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_20_k_100_n_10000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

In [12]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 50000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_10_k_100_n_50000 = np.zeros([n_test, 7])

privacy_level = 1.0

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(280,n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_10_k_100_n_50000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_10_k_100_n_50000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_10_k_100_n_50000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_10_k_100_n_50000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_10_k_100_n_50000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_10_k_100_n_50000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_10_k_100_n_50000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_10_k_100_n_50000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

KeyboardInterrupt: 

In [14]:

t = time.time()
for i in range(280,n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_10_k_100_n_50000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_10_k_100_n_50000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_10_k_100_n_50000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_10_k_100_n_50000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_10_k_100_n_50000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_10_k_100_n_50000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_10_k_100_n_50000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_10_k_100_n_50000)

281th test
282th test
283th test
284th test
285th test
286th test
287th test
288th test
289th test
290th test
291th test
292th test
293th test
294th test
295th test
296th test
297th test
298th test
299th test
300th test


array([[0.32999998, 0.54249996, 0.0275    , ..., 0.04      , 0.03551592,
        0.        ],
       [0.21499999, 0.60249996, 0.14999999, ..., 0.375     , 0.41506113,
        0.        ],
       [0.12      , 0.27500001, 0.25999999, ..., 0.0925    , 0.09138075,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [15]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 40000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_10_k_100_n_40000 = np.zeros([n_test, 7])

privacy_level = 1.0

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_10_k_100_n_40000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_10_k_100_n_40000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_10_k_100_n_40000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_10_k_100_n_40000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_10_k_100_n_40000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_10_k_100_n_40000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_10_k_100_n_40000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_10_k_100_n_40000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

In [16]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 30000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_10_k_100_n_30000 = np.zeros([n_test, 7])

privacy_level = 1.0

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_10_k_100_n_30000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_10_k_100_n_30000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_10_k_100_n_30000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_10_k_100_n_30000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_10_k_100_n_30000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_10_k_100_n_30000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_10_k_100_n_30000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_10_k_100_n_30000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

In [17]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 20000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_10_k_100_n_20000 = np.zeros([n_test, 7])

privacy_level = 1.0

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_10_k_100_n_20000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_10_k_100_n_20000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_10_k_100_n_20000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_10_k_100_n_20000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_10_k_100_n_20000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_10_k_100_n_20000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_10_k_100_n_20000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_10_k_100_n_20000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

In [2]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 10000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_10_k_100_n_10000 = np.zeros([n_test, 7])

privacy_level = 1.0

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_10_k_100_n_10000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_10_k_100_n_10000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_10_k_100_n_10000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_10_k_100_n_10000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_10_k_100_n_10000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_10_k_100_n_10000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_10_k_100_n_10000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_10_k_100_n_10000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

In [4]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 40000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_05_k_100_n_40000 = np.zeros([n_test, 7])

privacy_level = 0.5

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_05_k_100_n_40000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_05_k_100_n_40000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_05_k_100_n_40000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_05_k_100_n_40000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_05_k_100_n_40000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_05_k_100_n_40000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_05_k_100_n_40000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_05_k_100_n_40000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

In [5]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 30000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_05_k_100_n_30000 = np.zeros([n_test, 7])

privacy_level = 0.5

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_05_k_100_n_30000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_05_k_100_n_30000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_05_k_100_n_30000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_05_k_100_n_30000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_05_k_100_n_30000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_05_k_100_n_30000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_05_k_100_n_30000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_05_k_100_n_30000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

In [2]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 20000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_05_k_100_n_20000 = np.zeros([n_test, 7])

privacy_level = 0.5

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_05_k_100_n_20000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_05_k_100_n_20000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_05_k_100_n_20000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_05_k_100_n_20000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_05_k_100_n_20000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_05_k_100_n_20000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_05_k_100_n_20000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_05_k_100_n_20000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12

In [6]:
n_test = 300
n_permutation = 399
significance_level = 0.05
alphabet_size = 100
sample_size = 10000

###################
###################

data_gen = data_generator(device)

p1 = torch.ones(alphabet_size).div(alphabet_size)

bump_size = 0.005
p2 = p1.add(
    torch.remainder(
    torch.tensor(range(alphabet_size)),
    2
    ).add(-1/2).mul(2).mul(bump_size)
)
print(p2)



p_value_array_priv_05_k_100_n_10000 = np.zeros([n_test, 7])

privacy_level = 0.5

LDPclient = client(device, privacy_level)

server_elltwo = server_ell2(device, privacy_level)
server_elltwo_disc = server_ell2(device, privacy_level)
server_elltwo_trunc = server_ell2(device, privacy_level)

server_genrr = server_multinomial_genrr(device, privacy_level)
server_bitflip = server_multinomial_bitflip(device, privacy_level)



t = time.time()
for i in range(n_test):
    print(f"{i+1}th test")
    torch.manual_seed(i)
    data_y = data_gen.generate_multinomial_data(p1, sample_size)
    data_z = data_gen.generate_multinomial_data(p2, sample_size)
    LDPclient.load_data_multinomial(data_y, data_z, alphabet_size)
    
    data_lapu_y, data_lapu_z = LDPclient.release_lapu()
    server_elltwo.load_private_data_multinomial(data_lapu_y, data_lapu_z, alphabet_size)
    p_value_array_priv_05_k_100_n_10000[i,0] = server_elltwo.release_p_value_permutation(n_permutation)
    
    data_disclapu_y, data_disclapu_z = LDPclient.release_lapu()
    server_elltwo_disc.load_private_data_multinomial(data_disclapu_y, data_disclapu_z, alphabet_size)
    p_value_array_priv_05_k_100_n_10000[i,1] = server_elltwo_disc.release_p_value_permutation(n_permutation)
       
    data_genrr_y, data_genrr_z = LDPclient.release_genrr()
    server_genrr.load_private_data_multinomial(data_genrr_y, data_genrr_z, alphabet_size)
    p_value_array_priv_05_k_100_n_10000[i,2] = server_genrr.release_p_value_permutation(n_permutation)
    p_value_array_priv_05_k_100_n_10000[i,3] = server_genrr.release_p_value()
    
    data_bitflip_y, data_bitflip_z = LDPclient.release_bitflip()
    server_bitflip.load_private_data_multinomial(data_bitflip_y, data_bitflip_z, alphabet_size)
    p_value_array_priv_05_k_100_n_10000[i,4] = server_bitflip.release_p_value_permutation(n_permutation)
    p_value_array_priv_05_k_100_n_10000[i,5] = server_bitflip.release_p_value()

elapsed = time.time() - t

with open('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_05_k_100_n_10000.npy', 'wb') as f:
    np.save(f, p_value_array_priv_05_k_100_n_10000)

tensor([0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150,
        0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050, 0.0150, 0.0050,
        0.0150])
1th test
2th test
3th test
4th test
5th test
6th test
7th test
8th test
9th test
10th test
11th test
12