In [2]:
import numpy as np
import pandas as pd

# alpha = 4

In [12]:
p_value_array_priv_40_k_100_n_50000 = np.load('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_40_k_100_n_50000.npy')
(p_value_array_priv_40_k_100_n_50000<0.05).mean(axis = 0)

array([1., 1., 1., 1., 1., 1., 1.])

In [7]:
p_value_array_priv_40_k_100_n_40000 = np.load('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_40_k_100_n_40000.npy')
(p_value_array_priv_40_k_100_n_40000<0.05).mean(axis = 0)

array([1., 1., 1., 1., 1., 1., 1.])

In [13]:
p_value_array_priv_40_k_100_n_30000 = np.load('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_40_k_100_n_30000.npy')
(p_value_array_priv_40_k_100_n_30000<0.05).mean(axis = 0)

array([0.98333333, 0.98666667, 1.        , 1.        , 1.        ,
       1.        , 1.        ])

In [14]:
p_value_array_priv_40_k_100_n_20000 = np.load('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_40_k_100_n_20000.npy')
(p_value_array_priv_40_k_100_n_20000<0.05).mean(axis = 0)

array([0.91, 0.87, 1.  , 1.  , 1.  , 1.  , 1.  ])

In [15]:
p_value_array_priv_40_k_100_n_10000 = np.load('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_40_k_100_n_10000.npy')
(p_value_array_priv_40_k_100_n_10000<0.05).mean(axis = 0)

array([0.49666667, 0.48666667, 1.        , 1.        , 0.96666667,
       0.96666667, 1.        ])

# alpha = 2

In [66]:
sample_size_vec = [10000, 20000, 30000, 40000, 50000]
power_array_priv_20_k_100 = np.zeros([5,8])
for i, sample_size in enumerate(sample_size_vec):
    filename = '/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_20_k_100_n_' + str(sample_size) + '.npy'
    p_value_vec = np.load(filename)
    power_array_priv_20_k_100[i,np.arange(1,7+1)] = (p_value_vec<0.05).mean(axis = 0)
power_array_priv_20_k_100[:,0 ] = 10000*np.arange(1,5+1)
power_array_priv_20_k_100 = pd.DataFrame(power_array)
power_array_priv_20_k_100.columns = ["sample_size", "lapu", "disclapu", "genrr", "genrr_perm", "bitflip", "bitflip_perm", "truncNorm"]
power_array_priv_20_k_100.to_csv("power_array_priv_20_k_100.csv", index = False)

In [ ]:
power_array_priv_20_k_100

In [48]:
np.arange(2,8+1)

array([2, 3, 4, 5, 6, 7, 8])

In [20]:
p_value_array_priv_20_k_100_n_20000 = np.load('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_20_k_100_n_20000.npy')
(p_value_array_priv_20_k_100_n_20000<0.05).mean(axis = 0)

array([0.21      , 0.22666667, 0.13333333, 0.11666667, 0.54333333,
       0.54666667, 1.        ])

In [21]:
p_value_array_priv_20_k_100_n_10000 = np.load('/mnt/nas/users/mjm/LDPUts/simul/power/p_value_array_priv_20_k_100_n_10000.npy')
(p_value_array_priv_20_k_100_n_10000<0.05).mean(axis = 0)

array([0.14333333, 0.11333333, 0.11333333, 0.12666667, 0.21      ,
       0.21666667, 1.        ])

In [65]:



d_priv_20_k_100 = {
    "10000" : (p_value_array_priv_20_k_100_n_10000<0.05).mean(axis = 0),
    "20000" : (p_value_array_priv_20_k_100_n_20000<0.05).mean(axis = 0),
    "30000" : (p_value_array_priv_20_k_100_n_30000<0.05).mean(axis = 0),
    "40000" : (p_value_array_priv_20_k_100_n_40000<0.05).mean(axis = 0),
    "50000" : (p_value_array_priv_20_k_100_n_50000<0.05).mean(axis = 0)
}
pd.DataFrame(data = d_priv_20_k_100)

TypeError: Index(...) must be called with a collection of some kind, False was passed

In [32]:
np.vstack((p_value_array_priv_20_k_100_n_10000<0.05).mean(axis = 0), 
         (p_value_array_priv_20_k_100_n_20000<0.05).mean(axis = 0)
         )

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

10000     20000
0  0.143333  0.210000
1  0.113333  0.226667
2  0.113333  0.133333
3  0.126667  0.116667
4  0.210000  0.543333
5  0.216667  0.546667
6  1.000000  1.000000